---
apiVersion: v1
kind: Service
metadata:
  name: serviceauto
  namespace: srinathkl
spec:
  type: NodePort
  selector:
    author: sri
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30022 
