apiVersion: apps/v1
kind: Deployment
metadata:
  name: sri
  namespace: srinathkl
spec:
  replicas: 2
  selector:
    matchLabels:
      author: sri
      raja: rani
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: sr
      labels:
        author: sri
        raja: rani
    spec:
      containers:
        - name: srinath
          image: sreeharshav/rollingupdate:v5

