---
apiVersion: v1
kind: Service
metadata:
  name: sro
  namespace: srinathkl
spec:
  type: NodePort
  selector:
    author: sri
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30003
...
