---
apiVersion: v1
kind: Service
metadata:
  name: sri
    #namespace: srinathkl
spec:
  type: NodePort
  selector:
    author: sri
  ports:
    - protocol: TCP
      targetPort: 4444
      port: 4444
      nodePort: 30004
...
