---
apiVersion: v1
kind: ReplicationController
metadata:
  name: srinathapp
  labels:
    author: sri
    ty: raju
  namespace: srinathkl
spec:
  replicas: 2
  selector:
    name: sriapp
  template:
    metadata:
      name: srinathaap1
      labels:
        name: sriapp   
    spec:
     containers:
        - name: sricon
          image: ashokit/javawebapp
...
