---
apiVersion: v1
kind: Pod
metadata:
  name: srinm
  labels:
    sr: jk
spec:
  containers:
    - name: sr
      image: nginx
      volumeMounts:
        - mountPath: /data/ng
          name: myv
  volumes:
    - name: myv
      emptyDir: {}
...
