---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: srinathpv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/mydb
  storageClassName: local-storage
...
