---
apiVersion: v1
kind: PersistentVolume 
metadata:
  name: srinathpv
  labels:
    author: srinathk
    type: pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /tmp/srinathpv1
...
