---
apiVersion: v1
kind: Service
metadata:
  name: srinathservice
  labels:
    author: srinath
    type: service
spec:
  clusterIP: None
  ports:
    - targetPort: 3306
      port: 3306
  selector:
    type: stateful
...
